### ISSUE TITLE
Support images defined as string

### ISSUE THREAD

**Issue by jirikuncar** [jupyterhub/chartpress#10]
Add support for images defined as `<registry>/<repo>:<tag>`.

Possible solutions to keep compatibility with images defined as mapping:

1. check the image value in `values.yaml`
2. if it is mapping use current way of setting the dictionary;
3. else use formatted string `"{registry}/{repo}:{tag}".format(...)`

Please let me know what you think and I will send a PR.

**Comment by minrk** [comment]
I think making image a string makes the most sense, since that's how it's ~always used in the end. Feel free to make a PR!
