### ISSUE TITLE
1.0.0 release!!

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#103]
@minrk @manics @yuvipanda I suggest we release 1.0.0, this project has plenty of tests and is well documented and such I think.

It can be practically helpful to have more flexibility to communicate more information with the changes to versions when you can adjust major.minor.patch and not only adjust minor.patch, so I think we should go for a 1.0.0 release!

I hope to address #89 first before release, but otherwise think this is ready for the release.

**Comment by yuvipanda** [comment]
TIME TO DO IT!

**Comment by minrk** [comment]
Yup, go for it!

**Comment by consideRatio** [comment]
I closed #89 by merging #106 and also added a major refactor before the 1.0.0 in #105.

1.0.0 is now released!
