### ISSUE TITLE
Surprisingly large changes when index.yaml is updated?

### ISSUE THREAD

**Issue by manics** [jupyterhub/chartpress#104]
I started investigating https://github.com/jupyterhub/mybinder.org-deploy/issues/1706 by checking the changes to `index.yaml` in https://jupyterhub.github.io/helm-chart/

I noticed the changes were surprisingly large (I don't know if this is related to the above issue).

E.g. compare
https://github.com/jupyterhub/helm-chart/commit/f37566fa696b42ac0b44054420da51ff450d2b80
which seems to rewrite a large part of index.yaml, 1788 lines changed
with the previous change
https://github.com/jupyterhub/helm-chart/commit/c945feb801f9532fec4959fa46f082e5cbdc358b
which just adds the chart, 17 lines changed

I _think_ this is roughly where the change in behaviour started to occur.

I haven't had time to dig any further yet.

**Comment by manics** [comment]
In case it's related there's a weird issue with
https://jupyterhub.github.io/helm-chart/
where sometimes all the stable charts are missing. For example, earlier in the week (not sure when, I've had the browser tab open in the background):
![image](https://user-images.githubusercontent.com/1644105/99536776-b1d68980-29a2-11eb-9409-060fff025da4.png)

**Comment by betatim** [comment]
Seems like https://github.com/jupyterhub/helm-chart/commit/aefefd62bf0120be2f6a52a1530b0732dac12340 is the last good commit.

This is the Travis job that published the _next_ commit is https://travis-ci.com/github/jupyterhub/binderhub/jobs/426603797

**Comment by consideRatio** [comment]
__Large changes in index.yaml__

Yes I have noticed this too! I think it is a reordering of the large list where the sorting isn't reliable. It could be reliable sorting using one specific helm version, but unreliable sorting if using two different also. @betatim thanks for linking the build jobs! I see that those two used Helm version 2.16.12 and Helm version 3.4.0. Perhaps we have an issue now that there is a mix between Helm2/3?

__Stable version sometimes not showing?__

I introduced a bug, and then I fixed it. This is how it looks now. I pushed directly to the gh-pages branch without creating a PR in this case.

![image](https://user-images.githubusercontent.com/3837114/99772217-a7cf9a80-2b0a-11eb-9250-a40b0c9fff43.png)

**Comment by consideRatio** [comment]
I've figured this one out. This is because helm3 puts invalid charts in the bottom of a list, while helm2 that doesn't consider them invalid puts them next to the other helm charts.

By removing the invalid entries, or always publishing using helm3, we won't experience this any more.

**Comment by consideRatio** [comment]
Having removed the invalid helm charts, and then later triggered a build, this commit was added which seems good: https://github.com/jupyterhub/helm-chart/commit/d70d1f39421b58cd22b88e2bc1d9b5d1cbf70c4e
