### ISSUE TITLE
Publish chartpress on conda-forge

### ISSUE THREAD

**Issue by manics** [jupyterhub/chartpress#126]
### Proposed change
Add chartpress to conda-forge

### Alternative options
Don't add chartpress to conda-forge

### Who would use this feature?
Anyone who wants to manage their Z2JH development environment with conda-forge

### (Optional): Suggest a solution
I'll go ahead and create a recipe if no-one has a reason not too.

**Comment by consideRatio** [comment]
If you want this I'm +1 for (you) doing it. If suggest it because "maybe someone (but not me) wants it?" then I'm slanted towards we shouldn't do it as it locks into some future maintenance burden.

**Comment by manics** [comment]
It's for me, I've had one too many conda-pip conflicts 😃

**Comment by consideRatio** [comment]
Hey @manics, I've been starting to appreciate conda more and more thanks to `mamba`s improved performance, learning more about it, and seeing features like automerge in the feedstock repo's.

You didn't get started on this, right?

**Comment by manics** [comment]
Thanks for the reminder, I've just opened https://github.com/conda-forge/staged-recipes/pull/16061

**Comment by consideRatio** [comment]
Nice work @manics! Closing as completed via:
- https://anaconda.org/conda-forge/chartpress
- https://github.com/conda-forge/chartpress-feedstock
