### ISSUE TITLE
Avoid rebuilding an image already available in registry when two --platform flags are passed

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#132]
### Bug description (Broken expectation)

Chartpress doesn't recognize if an image is already available when passing multiple platforms and will instead rebuild the image.

### How to reproduce

- Make sure to update the imagePrefix below to a location you have push rights
- Make sure to install buildx and configure so you can use arm64

```
mkdir -p /tmp/test-chartpress/images/test-image
cd /tmp/test-chartpress

helm create test-chart

cat <<EOF > chartpress.yaml
charts:
  - name: test-chart
    imagePrefix: quay.io/consideratio/
    images:
      test-image: {}
EOF

cat <<EOF > images/test-image/Dockerfile
FROM python:3.8-slim
EOF

git init
git add .
git commit -m "initial commit"

# First push someplace
chartpress --builder docker-buildx --platform linux/amd64 --platform linux/arm64 --push

# I'd like this to not even try to build, cache or not, as the
# image is now available in the registry since the last command,
# which is what i want to be detected or similar at least unless
# we pass --force-push where that detection is ignored
chartpress --builder docker-buildx --platform linux/amd64 --platform linux/arm64 --push
```

### Relevant code

https://github.com/jupyterhub/chartpress/blob/cf43a15031d2703f7727133faeec5b46e3daab95/chartpress.py#L379-L382

https://github.com/jupyterhub/chartpress/blob/cf43a15031d2703f7727133faeec5b46e3daab95/chartpress.py#L412-L415

### Suggested change

I think we should opt out of this better safe than sorry logic and instead use a default behavior with higher performance and potentially a warning saying that it may have made the wrong decision, where the user can fall back to `--force-build` and `--force-push` if wanted.

@manics, you have become very knowledgeable about the multi-arch builds. WDYT?

**Comment by manics** [comment]
Why don't we do it properly, and check for all platforms?
https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.RegistryData.has_platform

**Comment by consideRatio** [comment]
@manics wieeeeeeeee omg yes!
