### ISSUE TITLE
add a `--file` flag to use a different `chartpress.yaml`

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/chartpress#170]
### Proposed change
In projects involving more than one chart, it would be useful to have a `--file` flag such that a specific `chartpress.yaml` file could be targeted, e.g. 

```
chartpress --file another-chartpress.yaml
```
### Alternative options
This behavior can be achieved by separating out charts via the directory structure and running `chartpress` in subdirectories, but this is sub-optimal, tedious and error-prone. 

### Who would use this feature?
Anyone building multiple charts in a single repo that don't all need to be built/packaged at the same cadence.

**Comment by manics** [comment]
This is very similar to https://github.com/jupyterhub/chartpress/issues/118
Do you mind adding your suggestion on that issue instead and we can consider them together?

**Comment by rokroskar** [comment]
Thanks for reminding me about that issue! They seem to be addressing pretty different things though, I'm not sure they should be wrapped into one. #118 is about relative path handling _after_ the `chartpress.yaml` file has already been parsed; this request is simply to allow one to specify an alternative `chartpress.yaml`. But maybe you have a solution in mind for #118 that makes this request here moot?

**Comment by rokroskar** [comment]
Actually, it looks like #118 has been fixed by #161 🎉  

At least I no longer get an error trying to publish a chart that has the `chartpress.yaml` file at the root of the repo. 😆
