### ISSUE TITLE
Reimplement current `chartpress --reset --tag`

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#174]
From https://github.com/jupyterhub/chartpress/pull/150#issuecomment-1059150383 in #150 @minrk and I discussed `chartpress --reset --tag`, which currently updates the Chart.yaml version, but not the images.

> > Only the Helm chart's version needs to be updated, not the images.
>
> True, and this is what chartpress --reset --tag x currently does (chart.resetVersion and chart.resetTag are set via different paths). This might be a bug! But we can make a new entrypoint, or add further clarification of what to do when, if that would be helpful.

I think its hard to understand and document the current `chartpress --reset` interaction with `--tag`, and it feels buggy that it influences the Chart.yaml version but not the images tag. So maybe we can iterate on this?

What about providing something like this, where we have  a use ase for `--reset-chart-version` specifically with #150?

```
chartpress --reset --reset-chart-version=1.2.3 --reset-image-tag=1.2.3
```

**Comment by minrk** [comment]
Here's a question about adding a separate argument: does it ever make sense to set them to different values? If not, it doesn't make sense to require setting two arguments always to the same value. It seems to me that `--reset ---tag X` should set the same tag _everywhere_, and it's purely a but that we only apply it to the chart at the moment. WDYT?
