### ISSUE TITLE
Pinning of ruamel.yaml versions?

### ISSUE THREAD

**Issue by leafty** [jupyterhub/chartpress#21]
Recent published versions of [ruamel.yaml](https://bitbucket.org/ruamel/yaml) have introduced breaking changes for chartpress. See:
- https://github.com/jupyterhub/chartpress/pull/17
- https://github.com/jupyterhub/chartpress/issues/19
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/831

To avoid this in the future, it might be a good idea to pin the version of `ruamel.yaml` to be used by chartpress. We can also use a narrow range of versions known to work.

**Comment by minrk** [comment]
Strict pinning is a bit of an antipattern in most Python packages due to shared environments. While this has occurred recently, it's rare and I think we can deal with it. *Users* pinning ruamel.yaml and other deps is definitely a valid choice, though. Just not a good plan for libraries.
