### ISSUE TITLE
required build is skipped if outside commit range

### ISSUE THREAD

**Issue by minrk** [jupyterhub/chartpress#23]
chartpress logic for whether to build/push an image currently doesn't check whether that image:tag exists. Instead, it *assumes* it does if `--commit-range` is specified and the last change is outside the range. This can be a faulty assumption in a number of cases, including:

- previous build or publish failed
- image prefix changed
- CI didn't build the relevant commit (e.g. due to aborting superseded builds)

Instead, we should modify the build-triggering condition to include a check for existence of the image:

- if image changed in commit range (current)
- **or** image doesn't exist

Alternately, we could skip the "didn't change" check, and only check for image existence (avoids triggering build if called with the same `--commit-range` twice).

**Comment by consideRatio** [comment]
Ah! This would save us a lot of trouble the next time Travis is unstable and merges to master causes failing builds etc, I figure that is why you created this issue :) Excellent!
