### ISSUE TITLE
Support semantic version for tags

### ISSUE THREAD

**Issue by porterde** [jupyterhub/chartpress#26]
I raised an issue against the zero-to-jupyterhub-k8s project jupyterhub/zero-to-jupyterhub-k8s#1038 but if I've understood the build process correctly the change is probably across both this project (to support version tags) and the zero-to-jupyterhub-k8s project (to modify the CI scripts).

**Comment by minrk** [comment]
Sounds like including the chart version in the image tag would be the thing to do
