### ISSUE TITLE
travis-ci seems to always rebuild images without skipping

### ISSUE THREAD

**Issue by clkao** [jupyterhub/chartpress#40]
(from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1260#issuecomment-488013001)

> in a local dev env, i see `Skipping build for jupyterhub/k8s-hub:0.9-c9f80ce, it already exists` when running chartpress. but this is somehow not the case on travis, for example: https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/526434320#L536

**Comment by clkao** [comment]
it appears docker on travis has [registry mirror configured](https://travis-ci.org/mpromonet/dockertest/jobs/574753565#L223). this made the image check failed, so chartpress would not skip build: https://travis-ci.org/jupyterhub/zero-to-jupyterhub-k8s/jobs/577422531#L561

**Comment by clkao** [comment]
This appears to be caused by https://github.com/moby/moby/issues/39120

**Comment by consideRatio** [comment]
@clkao, do you have a suggestion on a way forward here? I've tried to grasp the situation but I struggle to both grasp the problem fully and how to proceed to resolve it in a good way.

**Comment by consideRatio** [comment]
@clkao figured out a workaround for https://github.com/moby/moby/issues/39120, to reset `/etc/docker/daemon.json` to not include the registry mirror and restart the docker daemon.

```
sudo cat /etc/docker/daemon.json
echo '{"mtu": 1460}' | sudo dd of=/etc/docker/daemon.json
sudo systemctl restart docker
docker ps -a
```

With this knowledge, I think it is out of scope for chartpress to make a change. Should we close this issue?

**Comment by minrk** [comment]
@consideRatio yeah, maybe. if there's another easy way to check if `docker pull` would work (I'm assuming it would in this case), that would be awesome, but this is a sensible "not our fault" kind of thing.

**Comment by consideRatio** [comment]
Closing this issue as it is resolved with @clkao's docker-fix script that modifies `/etc/docker/daemon.json` to not include the registry mirror. This is also implemented within z2jh now.

https://github.com/jupyterhub/chartpress/blob/1e07bd0fc07d6bb5b6ea25fb17880f3966706a21/.travis.yml#L20-L21
