### ISSUE TITLE
Release 0.3.2

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#43]
I pushed a 0.3.2 tag after updating the CHANGELOG.md and updated the README.md to reflect changes to the provided `chartpress --help` output. These are the changes between https://github.com/jupyterhub/chartpress/compare/0.3.1...0.3.2. I also added https://github.com/jupyterhub/chartpress/commit/9ded86b3aa9f577d90ae14fe97c8b75c8cbc2b87 in order to return to a developer version `0.3.3.dev`.

Is it okay if we publish this tag to PyPI? The current PyPI maintainers of the [PyPI package chartpress](https://pypi.org/project/chartpress/) are @minrk, @willingc and @yuvipanda.

If it seems OK, then this is my understanding of what would need to be done to publish the new package on PyPI.

```sh
# checkout the tag
git checkout 0.3.2

# package
python3 setup.py bdist_wheel

# upload to PyPI
twine upload dist/chartpress-0.3.2-py3-none-any.whl
```

**Comment by yuvipanda** [comment]
@consideRatio i have added you as an owner on pypi :)

**Comment by consideRatio** [comment]
Wieeee I made a release ;)
