### ISSUE TITLE
Feature proposal: a flag to enforce builds

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#59]
Now that we check for local/remote existence of a image, we may end up failing to rebuild images if we want. I imagine a situation where we may want to get a fresher version of Ubuntu as base image for the hub image for example (`FROM ubuntu:18.04`), due to a security issue or similar, and that we want to re-push an update manually sometime.

I'm not sure.

**Comment by minrk** [comment]
Yeah, I think a `--force` flag (or `--force-build` if there's more than one thing we want to force separately) makes sense. I've definitely wanted this a few times in the past.
