### ISSUE TITLE
Setup more thorough pytest tests

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#67]
# More thorough testing

Partially closed by #67.

## Managing testing content
There is a challenge with testing chartpress relating to its interaction with the git repository. For proper testing, we would need to make commits and tags to some git repository, within some branch.

The best idea that allows for these modifications etc is to work with a pytest fixture to create a new temp directory, copying testing content there, run git init etc, and add tags etc.

Discarded ideas:
- Having a separate repository with testing content etc that we would clone.
- Checking out a new branch, adding tags etc, and then discarding the branch and returning to previous branch.

## Testing content

```
README.md
chartpress.yaml
images/Dockerfile
charttest/values.yaml
charttest/Chart.yaml
```

## Tests
- [ ] Test --force-build
- [ ] Test --push
- [ ] Test --force-push
- [x] Test static and rendered dynamic values (TAG, LAST_COMMIT) etc are passed to the Dockerfile as --build-arg.
- [x] Test that the latest of a) latest tagged commit and b) latest modifying commit is used.
- [x] Test --version
- [x] Test --reset
- [x] Test --skip-build
- [x] Test --publish-chart
- [x] Test --extra-message
- ...

**Comment by consideRatio** [comment]
### Managing testing content
I think its nice to not add another repo, and keep everything in this. I suggest the use of a test branch with one single helm chart for testing purposes that we run git init and add tags etc during tests. We could also reset the state of this testing content folder in between tests using checkout on the folder etc.

### Testing content

```
README.md
chartpress.yaml
images/Dockerfile
charttest/values.yaml
charttest/Chart.yaml
```

### Tests
- Make a change to README.md and verify that we don't update either Chart or images.
- Make a change to an image and verify that we update both image and chart version.
- Make a change to the chart only and verify that we update chart version only.
- Test static and rendered dynamic values (TAG, LAST_COMMIT) etc are passed to the Dockerfile as --build-arg. I wonder how we go about this... Can we extract something built from within the container?
- Test that the latest of a) latest tagged commit and b) latest modifying commit is used.
- Test --version
- Test --reset
- Test --skip-build
- ...

### Bonus tests
- Consider if we can test chart publishing in a way that doesn't start relying on external state.
-

**Comment by consideRatio** [comment]
# Technical notes

### Testing `--build-arg` passing
We want to be able to test passed --build-arg to the docker container somehow. I suggest we do it by letting the build fail or succeed depending on them.

**Comment by manics** [comment]
You could set a property and inspect it?
```
$ cat Dockerfile
FROM busybox
ARG BUILDVAR
LABEL a.b.c="$BUILDVAR"
```
```
$ docker build --build-arg BUILDVAR=123 -t tmp .
Sending build context to Docker daemon  2.763MB
Step 1/3 : FROM busybox
 ---> 19485c79a9bb
Step 2/3 : ARG BUILDVAR
 ---> Using cache
 ---> 92f11c430e8a
Step 3/3 : LABEL a.b.c="$BUILDVAR"
 ---> Running in 13ae3b249cea
Removing intermediate container 13ae3b249cea
 ---> bed27836d44a
Successfully built bed27836d44a
Successfully tagged tmp:latest
```
```
$ docker inspect -f {{.Config.Labels}} tmp
map[a.b.c:123]
```

**Comment by consideRatio** [comment]
@manics :heart:
