### ISSUE TITLE
backwards-incompatible changes to image tags

### ISSUE THREAD

**Issue by rokroskar** [jupyterhub/chartpress#71]
The changes introduced in #52 and subsequent iterations created a backward-incompatible image and chart tagging scheme (which consequently broke most of our CI/CD pipelines). I don't dislike the new scheme since it is also more aligned with how e.g. `setuptools_scm` handles versions but I wonder if it would be desirable to provide an option to use the "old-style" tags e.g. `<version>-<commit-sha>`?

**Comment by consideRatio** [comment]
@rokroskar, sorry for the breaking changes that wasn't properly documented, also sorry for making another breaking change in order to avoid a bug that was hard to resolve in 0.4.3.

See [CHANGELOG.md](CHANGELOG.md), and perhaps also https://github.com/helm/helm/issues/6710 that caused a lot of the issues.

**Comment by rokroskar** [comment]
Thanks @consideRatio, the new behavior seems like a big improvement, so no worries!

> Do you personally have need for such flag to retain the old way of writing out the version?

As long as the commit hash is still there I don't think so. It's also much better to have sortable tags so 👍 

I'm still confused about a few parts of this, however. My understanding is that a semver version like `1.0.0-12-abcd` would mean that this is a pre-release of 1.0.0. Therefore if I have a tag `1.0.0` and my repository is one commit past this tag, shouldn't the next tag be something like `1.0.1-1-efgh`? This is how versions are generated by [`setuptools_scm`](https://pypi.org/project/setuptools-scm/)` for example (though they don't use commit hashes). I realize that this isn't the behavior of `git describe` which is what you are using to generate the pieces of the tag, but I guess `git describe` doesn't claim to provide a valid semver. If e.g. helm is using semver spec to determine precedence then I guess that this versioning scheme will lead to problems. 

Well, after reading https://github.com/semver/semver/issues/200 I'm not sure what the correct behavior should be, but see also https://github.com/semver/semver/issues/394#issuecomment-347426836.

**Comment by consideRatio** [comment]
Quick incomplete response:

Semver 2 doesnt permit 2x use of - characters, right?

**Comment by rokroskar** [comment]
ah that part I didn't notice - but yes I guess you're right, the second one would need to be a `.`

**Comment by consideRatio** [comment]
Yes, the builds are no longer using semver in a way that makes perfect sense, due to the bug in helm that we workaround atm. We have prerelease syntax for builds after the release etc, ehile it is simply a build following the release.

**Comment by consideRatio** [comment]
I have started to think that we should not use the `+` to distinguish our charts, because anything following a + sign in a semver should not really matter but it really does for us.

So, lets lock in this current scheme.
