### ISSUE TITLE
What to do when tags are out of branch or is prefixed with a v?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/chartpress#89]
## Tags on commits not in current branch
Chartpress picks the version it sets, like 0.9.0-n123.gabc1234, based on the latest commit _on the current branch_. This means that if someone makes a patch release 0.9.1 with a cherry picked commit, it will be out of branch and chartpress will keep counting from 0.9.0. This is probably the preferred behavior, but it is a bit sensitive and requires the user to be aware about it.

I wonder if we perhaps should provide a warning and documentation about this in the readme?

## Invalid helm versions
Helm3 requires the Chart.yaml version to not have a leading `v`, so if someone makes a tag like v0.9.0 chartpress would still set the Chart.yaml version field to v0.9.0 but that would be invalid. So, what should we do about this? I think the right call is to allow the `v` in the tag but make the version set in chart.yaml be with the `v` stripped while letting the docker images have the `v` part of the tag still.

I'd love some input on this change.

This part is being closed by #106.

**Comment by yuvipanda** [comment]
> I think the right call is to allow the `v` in the tag but make the version set in chart.yaml be with the `v` stripped while letting the docker images have the `v` part of the tag still.

This seems reasonable

**Comment by yuvipanda** [comment]
> I wonder if we perhaps should provide a warning and documentation about this in the readme?

I think documenting how it figures out tag names is probably what we need for this.

**Comment by consideRatio** [comment]
@yuvipanda thank you for your input!! I love to get a confirmation that an action plan make sense, the challenging part often isn't doing something but doing the sensible thing ;D
