### ISSUE TITLE
Any edit to chartpress.yaml causes all images to rebuild

### ISSUE THREAD

**Issue by batpad** [jupyterhub/chartpress#97]
### Bug description

If I make any edit to chartpress.yaml, for eg. add a new image definition or edit the the `valuesPath` for an existing image, I expect it to not cause a bump in version numbers for all the images or fresh re-builds, but this seems to be what is happening.

Steps to reproduce:

 - Create chartpress.yaml referencing images to build
 - Run chartpress - images build
 - Make changes to one particular image or unrelated to the images folder
 - Run chartpress - does not rebuild any images that it does not need to.
 - Make an edit to chartpress.yaml - eg. change the valuesPath for an existing image

#### Expected behaviour

I expect chartpress to not rebuild any images since none of the contents of the images themselves have changed.

#### Actual behaviour

Chartpress now updates the version and rebuilds all images, even though nothing has actually changed in the images folder, just a change in the chartpress.yaml file.

### How to reproduce

Described above - let me know if it helps to create a repository with a simplified test case or so.

### Your personal set up

Encountered this on this repo https://github.com/developmentseed/osm-seed with chartpress running as part of a Github actions workflow, but I was able to reproduce this locally as well - ubuntu 20.04, running chartpress version 0.6.0.

(Thank you for an extremely useful project - let me know if I can help narrow this issue down).

**Comment by manics** [comment]
Hi! Could you take a look at https://github.com/jupyterhub/chartpress/issues/81 and see whether it also covers your use-case?

**Comment by batpad** [comment]
@manics I have mulled over this a bit and I have to admit that I'm not sure :-)

I **think** #81 would cover it if there's a way for me to specify that changes to `chartpress.yaml` don't cause a particular image to rebuild / get a version bump? Although, I'm not sure there's ever a reason I would want an image version bumped when making changes to the chartpress.yaml?

Looking at #81 again, I'm a bit confused if that only refers to the Chart version or also images of individual images (that cause image rebuilds) - this specific case is images getting version bumps and rebuilds when chartpress.yaml changes. If it seems like #81 also addresses this, happy to close here.

Also, this issue is not a blocker - just seemed unexpected that changing chartpress.yaml would cause images to rebuild, so filed - happy to close if this seems not really a bug / out of scope.

**Comment by manics** [comment]
I can see a case for changes to chartpress causing a rebuild- since chartpress defines your whole workflow you could in theory completely rewrite it, and you can't automatically predict what will change as a result. @consideRatio knows best though, so I'll leave it to him to close the issue if this is as expected.

**Comment by batpad** [comment]
Yep, I believe I had my mental model slightly wrong and did not fully think through cases where a change in the chartpress.yaml can cause the contents of image builds to change.

In this case, this seems to me to be reasonable and expected behaviour. And this behaviour does not cause any real issue other than a mild inconvenience at having to wait for all images to build when adding a new image to the chartpress config, for example.

Am closing this, thank you again for the response and for the project. Of course, someone can re-open, but for me this seems like expected behaviour with the understanding that chartpress.yaml changes can affect individual image builds.
